POST http://localhost:8080/events
Content-Type: application/json
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6InRlc3QzQGV4YW1wbGUuY29tIiwiZXhwIjoxNzM5NTkwNzA5LCJ1c2VySWQiOjF9.yL5Y8tjR9tCSv-MNvvjAYWunxAxri8KNynLTr9Kp9H0

{
  "name": "Test event",
  "description": "A test event",
  "location": "A test location",
  "dateTime": "2025-01-01T15:30:30.000Z"
}