DELETE http://localhost:8080/events/11
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6ImJyYW5kb25AZXhhbXBsZS5jb20iLCJleHAiOjE3Mzk3MzY3OTEsInVzZXJJZCI6Mn0.clRG_1J3m6N89WNLyBbQlu210wmgWgWYTSci8J1KZgY